[package]
name = "bbt"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bbt"
path = "src/main.rs"

[dependencies]
backbone = { path = "../backbone" }
clap = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
mimalloc = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
