[package]
name = "bbt"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
backbone = { path = "../backbone" }
clap = { workspace = true }
chrono = { workspace = true }
ignore = { workspace = true }
indicatif = { workspace = true }
console = { workspace = true }
mimalloc = "0.1.39"
qdrant-client = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
walkdir = { workspace = true }
